name: user_repository
description: user repo
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5
  firebase_auth: 4.17.5
  cloud_firestore: 4.15.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
